version: '3.8'

services:
  jenkins-blueocean:
    image: jenkinsci/blueocean
    container_name: jenkins-blueocean
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
